"""create trade proposals table

Revision ID: cce2857ca2b8
Revises: 
Create Date: 2026-08-17 11:56:11.008120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce2857ca2b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('primary_strategy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_trade_proposals_signal_id'), 'trade_proposals', ['signal_id'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_trade_proposals_symbol'), 'trade_proposals', ['symbol'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_trade_proposals_user_id'), 'trade_proposals', ['user_id'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_trade_proposals_user_id'), table_name='trade_proposals', schema='ai')
    op.drop_index(op.f('ix_ai_trade_proposals_symbol'), table_name='trade_proposals', schema='ai')
    op.drop_index(op.f('ix_ai_trade_proposals_signal_id'), table_name='trade_proposals', schema='ai')
    op.drop_table('trade_proposals', schema='ai')
    # ### end Alembic commands ###
