# ------------------ Trade Proposal Router Feature -----------------------
"""
FastAPI REST router for trade proposal management, risk evaluation trigger (Agent 4),
and paper trade execution pipeline gate (Agent 5).
"""

from uuid import UUID

from fastapi import APIRouter, Depends, Header, HTTPException, status
from sqlalchemy.orm import Session

from src.database import get_db
from src.execution_service import ExecutionService
from src.risk_service import RiskService
from src.schemas import (
    ExecutionResultResponse,
    RiskEvaluationResponse,
    TradeProposalCreate,
    TradeProposalResponse,
)
from src.trade_proposal_service import TradeProposalService

router = APIRouter(prefix="/trade-proposals", tags=["Trade Proposals"])
service = TradeProposalService()
risk_service = RiskService()
execution_service = ExecutionService()


# ------------------ Get All Proposals Endpoint -----------------------
@router.get("", response_model=list[TradeProposalResponse])
def get_all_proposals(user_id: UUID | None = None, db: Session = Depends(get_db)):
    """
    Retrieves all trade proposals stored in the database, optionally filtered by user ID.
    """
    return service.get_all_proposals(db, user_id)


# ------------------ Create Trade Proposal Endpoint -----------------------
@router.post(
    "", response_model=TradeProposalResponse, status_code=status.HTTP_201_CREATED
)
def create_proposal(proposal_in: TradeProposalCreate, db: Session = Depends(get_db)):
    """
    Creates and persists a new trade proposal generated by quantitative signal engines.
    """
    return service.create_proposal(db, proposal_in)


# ------------------ Get Proposal By ID Endpoint -----------------------
@router.get("/{proposal_id}", response_model=TradeProposalResponse)
def get_proposal(proposal_id: UUID, db: Session = Depends(get_db)):
    """
    Retrieves a single trade proposal by its UUID.
    """
    return service.get_proposal(db, proposal_id)


# ------------------ Evaluate Proposal Risk Endpoint (Agent 4) -----------------------
@router.post("/{proposal_id}/risk-evaluation", response_model=RiskEvaluationResponse)
def evaluate_proposal_risk(
    proposal_id: UUID,
    user_id: UUID | None = None,
    x_user_id: UUID | None = Header(default=None, alias="X-User-Id"),
    db: Session = Depends(get_db),
):
    """
    Agent 4 Risk Evaluation Engine.
    Evaluates position sizing, single asset concentration limits, portfolio exposure caps,
    and stop-loss distance rules for the specified trade proposal.
    """
    effective_user_id = user_id or x_user_id
    if not effective_user_id:
        raise HTTPException(
            status_code=400,
            detail="Missing user_id query parameter or X-User-Id header.",
        )
    try:
        evaluation = risk_service.evaluate_proposal(db, proposal_id, effective_user_id)
        if not evaluation:
            raise HTTPException(status_code=404, detail="Trade proposal not found.")
        return evaluation
    except PermissionError as e:
        raise HTTPException(status_code=403, detail=str(e)) from e
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e


# ------------------ Get Proposal Risk Evaluation Endpoint -----------------------
@router.get("/{proposal_id}/risk", response_model=RiskEvaluationResponse)
def get_proposal_risk(
    proposal_id: UUID,
    user_id: UUID | None = None,
    x_user_id: UUID | None = Header(default=None, alias="X-User-Id"),
    db: Session = Depends(get_db),
):
    """
    Retrieves the latest Risk Engine evaluation result for a trade proposal.
    """
    effective_user_id = user_id or x_user_id
    if not effective_user_id:
        raise HTTPException(
            status_code=400,
            detail="Missing user_id query parameter or X-User-Id header.",
        )
    try:
        evaluation = risk_service.get_latest_evaluation(
            db, proposal_id, effective_user_id
        )
        if not evaluation:
            raise HTTPException(
                status_code=404, detail="Risk evaluation not found for this proposal."
            )
        return evaluation
    except PermissionError as e:
        raise HTTPException(status_code=403, detail=str(e)) from e


# ------------------ Execute Proposal Endpoint (Agent 5) -----------------------
@router.post(
    "/{proposal_id}/execute",
    response_model=ExecutionResultResponse,
    summary="Agent 5: Execute approved paper trade",
    description=(
        "Executes a RISK_APPROVED trade proposal as a paper trade. "
        "Sends an immutable fill request to market-service. Idempotent execution."
    ),
)
def execute_proposal(
    proposal_id: UUID,
    user_id: UUID | None = None,
    x_user_id: UUID | None = Header(default=None, alias="X-User-Id"),
    db: Session = Depends(get_db),
):
    """
    Agent 5 Paper Execution Pipeline Gate.
    Verifies RISK_APPROVED status and forwards immutable order fill request to market-service.
    """
    effective_user_id = user_id or x_user_id
    if not effective_user_id:
        raise HTTPException(
            status_code=400,
            detail="Missing user_id query parameter or X-User-Id header.",
        )
    return execution_service.execute_proposal(db, proposal_id, effective_user_id)
